### PR TITLE
bug : exclude suggestion from assignment

### LINKED ISSUE #4544: Improve assignment bot logic
The assignment bot should only assign an issue to a particular user if the user comments `!assign` or `!assign me` or `please !assign me`

https://github.com/codinasion/codinasion/blob/0fa9dad5c599f318a8d417b4987e4507afc16b66/github-bots/assign-me/src/index.ts#L8

### Reference

Screenshot from 2023-07-19 23-54-44

### PR DESCRIPTION
**Pull request by ThaungThanHan**
## 📑 Description
In this pull request, I have changed the logic of the bot to exclude suggestion from assignment. So, In this case, I prevent the bot to assign if the person who creates the issue comments "!assign".
copilot:summary

## 🐞 Related Issue

Closes #4544 

## 📋 Explanation of changes
I have added a condition if issue owner is the same as comment creator, the bot will not proceed with the assignment. In this case, we can prevent the bot from assigning the owner when he/she suggests "!assign" command to other contributors.
copilot:walkthrough

copilot:poem

### CODE REVIEW

File: github-bots/assign-me/src/index.ts [hunk 1]
```diff
@@ -6,40 +6,45 @@ export = (app: Probot) => {
...
-          await context.octokit.issues.addAssignees(assign);
-        }
-        // if issue is assigned to the comment author
-        else if (
-          context.payload.issue.assignee.login ===
-          context.payload.comment.user.login
+      // Check if issue creator is comment creator
+      const commentCreator = context.payload.comment.user.login;
+      const issueCreator = context.payload.issue.user.login;
+      if (issueCreator !== commentCreator) {
```
Comment (harshraj8843) [inline github-bots/assign-me/src/index.ts:12]: For now, this will work 👍🏻 

But we should also consider that team members can also suggest

**Review by harshraj8843 — APPROVED** [review]
Thanks for contributing 🤗
